### ISSUE TITLE
Remove data files from package

### ISSUE THREAD

**Issue by p-s-vishnu** [p-s-vishnu/cassava-leaf-disease-classification-archive#10]
Make sure to reduce size of repo/package.

**Comment by VpkPrasanna** [comment]
we need to check the size of the package  Now as we have removed the data files  . Any idea on this how can we proceed with this @p-s-vishnu

**Comment by p-s-vishnu** [comment]
Can you check this link whether it makes sense : https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

We will have to keep few files in future for testing purpose so if it doesnt work then we will keep them as test images.

**Comment by p-s-vishnu** [comment]
Closing with status won't fix
