### ISSUE TITLE
 inference with Fast API

### ISSUE THREAD

**Issue by VpkPrasanna** [p-s-vishnu/cassava-leaf-disease-classification-archive#15]
I will implement the inference with fast API as a backend

**Comment by p-s-vishnu** [comment]
@VpkPrasanna If you created this issue for the purpose of creating webapp then I will not put this as a priority at the moment.
Streamlit app will not need an api if we are invoking the code through a package something like:

```python
from cassava.pretrained import get_model

model = get_model('resnet50')  # We can directly use this model to infer in the app
```

So in my opinion first we will have to package this and then later as an added feature we can have an api if anyone wants to consume through their webapp/interface, makes sense?

**Comment by VpkPrasanna** [comment]
> @VpkPrasanna If you created this issue for the purpose of creating webapp then I will not put this as a priority at the moment.
> Streamlit app will not need an api if we are invoking the code through a package something like:
> 
> ```python
> from cassava.pretrained import get_model
> 
> model = get_model('resnet50')  # We can directly use this model to infer in the app
> ```
> 
> So in my opinion first we will have to package this and then later as an added feature we can have an api if anyone wants to consume through their webapp/interface, makes sense?

Yeah i totally agree with you . I saw some small demo to create a streamlit app so i can work on that .

**Comment by VpkPrasanna** [comment]
This issue can also be closed as it is completed @p-s-vishnu
