### ISSUE TITLE
Create WebApp and Deploy to Heroku

### ISSUE THREAD

**Issue by p-s-vishnu** [p-s-vishnu/cassava-leaf-disease-classification-archive#20]

**Comment by VpkPrasanna** [comment]
Hey @p-s-vishnu  i have added the code for streamlit do review it

**Comment by p-s-vishnu** [comment]
Webapp complete however deployment to heroku free tier account failed due to 500 mb limit, we can create a separate issue for the deployment and tackle this. Closing this issue.
